### ISSUE TITLE
keep getting error 200

### ISSUE THREAD

**Issue by CaptainMaarten** [MadeBaruna/paimon-moe#574] opened 2024-07-29 13:12 UTC
cant really use the site to get my pity, every method i tried on the side gives me error 200
![image](https://github.com/user-attachments/assets/592fbf68-ce87-45da-9857-961765866f43)

**Comment by jouwana** [comment] 2024-07-29 18:09
i think the issue is that the web api / link that hoyo uses for pulls changed
it used to be webstatic, but now it is 'gs.hoyoverse'
e.g.:
it used to be:
webstatic-sea.hoyoverse.com/genshin/event/e20190909gacha-
now its:
gs.hoyoverse.com/genshin/event/e20190909gacha-

so it cant read it anymore

**Comment by MikuuH** [comment] 2024-07-30 07:37
I have a new link displayed in my console, but it still doesn't work. The site issues a 200 code. If you try the first method, you cannot find the wish history url! Make sure to open the wish history first!

```
Copy the wish history table!
Checking in 1 OK
https://gs.hoyoverse.com/genshin/event/e20190909gacha
```

Although my story is open right now.

**Comment by jouwana** [comment] 2024-07-30 09:27
> I have a new link displayed in my console, but it still doesn't work. The site issues a 200 code. If you try the first method, you cannot find the wish history url! Make sure to open the wish history first!
> 
> ```
> Copy the wish history table!
> Checking in 1 OK
> https://gs.hoyoverse.com/genshin/event/e20190909gacha
> ```
> 
> Although my story is open right now.


yeah i think they change the api itself as well, so not just the link, that should be why the auto doesnt work as well.

If you go to pullrequest #572 they shouldve changed jt and applied a fix, problem is it hasnt been merged yet

**Comment by jogerj** [comment] 2024-07-30 09:30
is fixed by https://github.com/MadeBaruna/paimon-moe/commit/4d9c85195e3aae428ab49000b89e071c70d2a652

**Closed** 2024-08-04 14:50 UTC
