### ISSUE TITLE
Not calculating resin for EXP books

### ISSUE THREAD

**Issue by speedisparrow** [MadeBaruna/paimon-moe#22] opened 2021-03-25 19:10 UTC
The todo list does not calculate the amount of resin required to farm exp books. Under the resin section it does not say anything about exp books
![image](https://user-images.githubusercontent.com/75000094/113635789-1e86b380-9626-11eb-8c36-4860e395c587.png)

**Comment by MadeBaruna** [comment] 2021-03-26 13:32
It's should have calculate resin for talent book, can you share some screenshot please?

And please separate the google drive issue to a new issue, thanks!

**Comment by speedisparrow** [comment] 2021-04-05 22:49
Edited it. I meant to say exp books not talent books.

**Comment by MadeBaruna** [comment] 2021-04-06 03:04
Duplicate of #10

**Closed by MadeBaruna** 2021-04-06 03:04 UTC
Labels: need confirmation
